[2022-09-06 17:50:40,443] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-09-06T17:50:27.109054+00:00 [queued]>
[2022-09-06 17:50:40,458] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-09-06T17:50:27.109054+00:00 [queued]>
[2022-09-06 17:50:40,459] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-06 17:50:40,460] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-09-06 17:50:40,461] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-06 17:50:40,481] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): cleaned_data_message> on 2022-09-06 17:50:27.109054+00:00
[2022-09-06 17:50:40,490] {standard_task_runner.py:52} INFO - Started process 200 to run task
[2022-09-06 17:50:40,495] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_cleaning_dag', 'cleaned_data_message', 'manual__2022-09-06T17:50:27.109054+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/data_cleaning_dag/data_cleaning.py', '--cfg-path', '/tmp/tmpd_6l5n26', '--error-file', '/tmp/tmpfa0r64co']
[2022-09-06 17:50:40,498] {standard_task_runner.py:80} INFO - Job 14: Subtask cleaned_data_message
[2022-09-06 17:50:40,605] {task_command.py:371} INFO - Running <TaskInstance: data_cleaning_dag.cleaned_data_message manual__2022-09-06T17:50:27.109054+00:00 [running]> on host ffa74c704a13
[2022-09-06 17:50:40,722] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_cleaning_dag
AIRFLOW_CTX_TASK_ID=cleaned_data_message
AIRFLOW_CTX_EXECUTION_DATE=2022-09-06T17:50:27.109054+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-06T17:50:27.109054+00:00
[2022-09-06 17:50:40,725] {logging_mixin.py:115} INFO - Data successfully cleaned
[2022-09-06 17:50:40,727] {python.py:173} INFO - Done. Returned value was: None
[2022-09-06 17:50:40,749] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=data_cleaning_dag, task_id=cleaned_data_message, execution_date=20220906T175027, start_date=20220906T175040, end_date=20220906T175040
[2022-09-06 17:50:40,789] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-06 17:50:40,840] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
